// GENERATED by tools/gen_settings.py from tools/sources.yaml. Do not edit by hand.
import Toybox.Lang;

//! Property keys, limits and defaults shared by Settings.mc and the generated resources.
module SettingsKeys {
    const SKIN_ID = "skinId";
    const PAGE_COUNT = "pageCount";
    const SECONDS_HAND_MODE = "secondsHandMode";
    const SECOND_TIME_ZONE_OFFSET_MINUTES = "secondTimeZoneOffsetMinutes";
    const SECOND_TIME_ZONE_OFFSET_MINUTES_DEFAULT = 0;
    const SECOND_TIME_ZONE_OFFSET_MINUTES_MIN = -720;
    const SECOND_TIME_ZONE_OFFSET_MINUTES_MAX = 840;
    const WEATHER_REFRESH_MINUTES = "weatherRefreshMinutes";
    const WEATHER_REFRESH_MINUTES_DEFAULT = 15;
    const WEATHER_REFRESH_MINUTES_MIN = 5;
    const WEATHER_REFRESH_MINUTES_MAX = 120;
    const PRESSURE_UNIT = "pressureUnit";
    const PRESSURE_UNIT_DEFAULT = "hPa";
    var PRESSURE_UNIT_OPTIONS as Array<String> = ["hPa", "mmHg", "inHg"];
    const HEALTH_ARC_TOP = "healthArcTop";
    const HEALTH_ARC_TOP_DEFAULT = "bodyBattery";
    var HEALTH_ARC_TOP_OPTIONS as Array<String> = ["bodyBattery", "stress", "spo2", "hrv"];
    const HEALTH_ARC_BOTTOM = "healthArcBottom";
    const HEALTH_ARC_BOTTOM_DEFAULT = "stress";
    var HEALTH_ARC_BOTTOM_OPTIONS as Array<String> = ["bodyBattery", "stress", "spo2", "hrv"];
    const EFFECTS_INTENSITY = "effectsIntensity";
    const EFFECTS_INTENSITY_DEFAULT = "normal";
    var EFFECTS_INTENSITY_OPTIONS as Array<String> = ["low", "normal", "high"];
    const SHOW_SUN_TIMES = "showSunTimes";
    const SHOW_SUN_TIMES_DEFAULT = true;
    const SHOW_MOON_PHASE_LABEL = "showMoonPhaseLabel";
    const SHOW_MOON_PHASE_LABEL_DEFAULT = true;
    const EFFECTS_ENABLED = "effectsEnabled";
    const EFFECTS_ENABLED_DEFAULT = true;
    const EFFECTS_ON_WRIST_RAISE_ONLY = "effectsOnWristRaiseOnly";
    const EFFECTS_ON_WRIST_RAISE_ONLY_DEFAULT = true;
    const MAX_PAGES = 6;
    const SLOTS_PER_PAGE = 5;
    const DEFAULT_PAGE_COUNT = 3;
    const DEFAULT_SKIN_ID = "classic";
    const DEFAULT_SECONDS_HAND_MODE = "skin";
    const EMPTY_SOURCE_ID = "Empty";
    //! Ordered as in sources.yaml. Phone settings store indices into these lists, so only append.
    var SKIN_IDS as Array<String> = ["classic", "minimal", "sport"];
    var SECONDS_HAND_MODES as Array<String> = ["skin", "always", "awakeOnly", "never"];
    var SOURCE_IDS as Array<String> = ["Empty", "Battery", "Steps", "HeartRate", "Date", "DayOfWeek", "BodyBattery", "Stress", "Calories", "Distance", "FloorsClimbed", "Notifications", "Weather", "Sunrise", "Sunset", "SecondTimeZone", "Altitude", "SolarIntensity", "ActiveMinutes"];
    var PAGE_TYPE_IDS as Array<String> = ["generic", "weather", "health"];
    var PAGE_TYPE_KEYS as Array<String> = ["page1type", "page2type", "page3type", "page4type", "page5type", "page6type"];
    var DEFAULT_PAGE_TYPES as Array<String> = ["generic", "weather", "health", "generic", "generic", "generic"];
    var SLOT_KEYS as Array<Array<String>> = [
        ["page1slot1", "page1slot2", "page1slot3", "page1slot4", "page1slot5"],
        ["page2slot1", "page2slot2", "page2slot3", "page2slot4", "page2slot5"],
        ["page3slot1", "page3slot2", "page3slot3", "page3slot4", "page3slot5"],
        ["page4slot1", "page4slot2", "page4slot3", "page4slot4", "page4slot5"],
        ["page5slot1", "page5slot2", "page5slot3", "page5slot4", "page5slot5"],
        ["page6slot1", "page6slot2", "page6slot3", "page6slot4", "page6slot5"],
    ];
    var DEFAULT_SLOTS as Array<Array<String>> = [
        ["Steps", "HeartRate", "Battery", "Date", "BodyBattery"],
        ["Weather", "Sunrise", "Sunset", "Notifications", "SecondTimeZone"],
        ["Calories", "Distance", "FloorsClimbed", "Stress", "ActiveMinutes"],
        ["Empty", "Empty", "Empty", "Empty", "Empty"],
        ["Empty", "Empty", "Empty", "Empty", "Empty"],
        ["Empty", "Empty", "Empty", "Empty", "Empty"],
    ];

    //! On-device editor complication id for a 0-based page and slot.
    function complicationUid(page as Number, slot as Number) as Number {
        return (page + 1) * 10 + (slot + 1);
    }

    //! 0-based page for an editor complication id.
    function pageForUid(uid as Number) as Number {
        return uid / 10 - 1;
    }

    //! 0-based slot for an editor complication id.
    function slotForUid(uid as Number) as Number {
        return uid % 10 - 1;
    }
}
