// GENERATED by tools/gen_settings.py from tools/sources.yaml. Do not edit by hand.
import Toybox.Complications;
import Toybox.Lang;

//! Property keys, limits and defaults shared by Settings.mc and the generated resources.
module SettingsKeys {
    const SKIN_ID = "skinId";
    const PAGE_COUNT = "pageCount";
    const SECONDS_HAND_MODE = "secondsHandMode";
    const SECOND_TIME_ZONE_OFFSET_MINUTES = "secondTimeZoneOffsetMinutes";
    const SECOND_TIME_ZONE_OFFSET_MINUTES_DEFAULT = 0;
    const SECOND_TIME_ZONE_OFFSET_MINUTES_MIN = -720;
    const SECOND_TIME_ZONE_OFFSET_MINUTES_MAX = 840;
    const WEATHER_REFRESH_MINUTES = "weatherRefreshMinutes";
    const WEATHER_REFRESH_MINUTES_DEFAULT = 15;
    const WEATHER_REFRESH_MINUTES_MIN = 5;
    const WEATHER_REFRESH_MINUTES_MAX = 120;
    const PRESSURE_UNIT = "pressureUnit";
    const PRESSURE_UNIT_DEFAULT = "hPa";
    var PRESSURE_UNIT_OPTIONS as Array<String> = ["hPa", "mmHg", "inHg"];
    const HEALTH_CHART = "healthChart";
    const HEALTH_CHART_DEFAULT = "bodyBattery";
    var HEALTH_CHART_OPTIONS as Array<String> = ["bodyBattery", "stress", "spo2", "heartRate"];
    const EFFECTS_INTENSITY = "effectsIntensity";
    const EFFECTS_INTENSITY_DEFAULT = "normal";
    var EFFECTS_INTENSITY_OPTIONS as Array<String> = ["low", "normal", "high"];
    const SHOW_SUN_TIMES = "showSunTimes";
    const SHOW_SUN_TIMES_DEFAULT = true;
    const SHOW_MOON_PHASE_LABEL = "showMoonPhaseLabel";
    const SHOW_MOON_PHASE_LABEL_DEFAULT = true;
    const EFFECTS_ENABLED = "effectsEnabled";
    const EFFECTS_ENABLED_DEFAULT = true;
    const EFFECTS_ON_WRIST_RAISE_ONLY = "effectsOnWristRaiseOnly";
    const EFFECTS_ON_WRIST_RAISE_ONLY_DEFAULT = true;
    const SHOW_COLOUR_SWATCHES = "showColourSwatches";
    const SHOW_COLOUR_SWATCHES_DEFAULT = false;
    const MAX_PAGES = 6;
    const SLOTS_PER_PAGE = 5;
    const DEFAULT_PAGE_COUNT = 3;
    const DEFAULT_SKIN_ID = "classic";
    const DEFAULT_SECONDS_HAND_MODE = "skin";
    const EMPTY_SOURCE_ID = "Empty";
    //! Ordered as in sources.yaml. Phone settings store indices into these lists, so only append.
    var SKIN_IDS as Array<String> = ["classic", "minimal", "sport"];
    var SECONDS_HAND_MODES as Array<String> = ["skin", "always", "awakeOnly", "never"];
    var SOURCE_IDS as Array<String> = ["Empty", "Battery", "Steps", "HeartRate", "Date", "DayOfWeek", "BodyBattery", "Stress", "Calories", "Distance", "FloorsClimbed", "Notifications", "Weather", "Sunrise", "Sunset", "SecondTimeZone", "Altitude", "SolarIntensity", "ActiveMinutes", "NextEvent", "PulseOx", "RespirationRate", "RecoveryTime", "SleepScore", "TrainingStatus", "Vo2Max", "Barometer", "HighLowTemp", "Humidity", "Wind", "RainChance", "UvIndex", "FeelsLike", "BatteryDays", "StepGoal"];
    var PAGE_TYPE_IDS as Array<String> = ["generic", "weather", "health"];
    var HAND_STYLES as Array<String> = ["skin", "baton", "dauphine", "arrow", "line", "skeleton"];
    //! System complication type per entry of SOURCE_IDS, -1 when there is none.
    var SOURCE_COMPLICATION_TYPES as Array<Number> = [-1, Complications.COMPLICATION_TYPE_BATTERY as Number, Complications.COMPLICATION_TYPE_STEPS as Number, Complications.COMPLICATION_TYPE_HEART_RATE as Number, Complications.COMPLICATION_TYPE_DATE as Number, Complications.COMPLICATION_TYPE_WEEKDAY_MONTHDAY as Number, Complications.COMPLICATION_TYPE_BODY_BATTERY as Number, Complications.COMPLICATION_TYPE_STRESS as Number, Complications.COMPLICATION_TYPE_CALORIES as Number, -1, Complications.COMPLICATION_TYPE_FLOORS_CLIMBED as Number, Complications.COMPLICATION_TYPE_NOTIFICATION_COUNT as Number, Complications.COMPLICATION_TYPE_CURRENT_TEMPERATURE as Number, Complications.COMPLICATION_TYPE_SUNRISE as Number, Complications.COMPLICATION_TYPE_SUNSET as Number, -1, Complications.COMPLICATION_TYPE_ALTITUDE as Number, Complications.COMPLICATION_TYPE_SOLAR_INPUT as Number, Complications.COMPLICATION_TYPE_INTENSITY_MINUTES as Number, Complications.COMPLICATION_TYPE_CALENDAR_EVENTS as Number, Complications.COMPLICATION_TYPE_PULSE_OX as Number, Complications.COMPLICATION_TYPE_RESPIRATION_RATE as Number, Complications.COMPLICATION_TYPE_RECOVERY_TIME as Number, Complications.COMPLICATION_TYPE_SLEEP_SCORE as Number, Complications.COMPLICATION_TYPE_TRAINING_STATUS as Number, Complications.COMPLICATION_TYPE_VO2MAX_RUN as Number, Complications.COMPLICATION_TYPE_SEA_LEVEL_PRESSURE as Number, Complications.COMPLICATION_TYPE_HIGH_LOW_TEMPERATURE as Number, -1, -1, -1, -1, -1, -1, -1];
    var DEFAULT_PAGE_TYPES as Array<String> = ["generic", "weather", "health", "generic", "generic", "generic"];
    //! Default source index (into SOURCE_IDS) per page and slot.
    var DEFAULT_SLOTS as Array<Array<Number>> = [
        [2, 3, 1, 19, 6],
        [12, 13, 14, 11, 15],
        [8, 9, 10, 7, 18],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
    ];

    //! Property key of a 0-based page and slot (built on demand, only at reload).
    function slotKey(page as Number, slot as Number) as String {
        return "page" + (page + 1) + "slot" + (slot + 1);
    }

    //! Property key of a 0-based page's type.
    function pageTypeKey(page as Number) as String {
        return "page" + (page + 1) + "type";
    }

    //! Property key of a 0-based page's hand style.
    function handsKey(page as Number) as String {
        return "page" + (page + 1) + "hands";
    }

    //! Default source ids of a 0-based page.
    function defaultSlotIds(page as Number) as Array<String> {
        var row = DEFAULT_SLOTS[page];
        var result = [] as Array<String>;
        for (var i = 0; i < row.size(); i++) {
            result.add(SOURCE_IDS[row[i]]);
        }
        return result;
    }

    //! On-device editor complication id for a 0-based page and slot.
    function complicationUid(page as Number, slot as Number) as Number {
        return (page + 1) * 10 + (slot + 1);
    }

    //! 0-based page for an editor complication id.
    function pageForUid(uid as Number) as Number {
        return uid / 10 - 1;
    }

    //! 0-based slot for an editor complication id.
    function slotForUid(uid as Number) as Number {
        return uid % 10 - 1;
    }
}
