# /// script
# requires-python = ">=3.11"
# dependencies = ["cairosvg", "pillow", "pyyaml"]
# ///
"""Rasterise assets/icons/src/*.svg to per-device PNG drawables.

For every product in manifest.xml the device pack (simulator.json, compiler.json) gives the
screen width and display type. Each icon is rendered at its group's percent of the screen
width (tools/icons.yaml). MIP displays get colours quantised to the 64 colour palette and a
1 bit alpha. Output goes to resources-<device>/drawables/ic_<name>.png plus a generated
icons.xml declaring the bitmaps.

Rendering uses cairosvg when importable, else the rsvg-convert binary. Run with
    uv run tools/gen_icons.py        (uv installs cairosvg, pillow and pyyaml in an isolated env)
or  python3 tools/gen_icons.py       (needs cairosvg or rsvg-convert, plus pillow and pyyaml)
"""

from __future__ import annotations

import io
import json
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Any, cast

os.environ.setdefault("DYLD_FALLBACK_LIBRARY_PATH", "/opt/homebrew/lib")

import yaml  # type: ignore[import-untyped]  # noqa: E402
from PIL import Image  # noqa: E402

TOOLS_DIR = Path(__file__).resolve().parent
PROJECT_DIR = TOOLS_DIR.parent
SRC_DIR = PROJECT_DIR / "assets/icons/src"
ICONS_FILE = TOOLS_DIR / "icons.yaml"
MANIFEST = PROJECT_DIR / "manifest.xml"
DEVICES_DIR = Path.home() / "Library/Application Support/Garmin/ConnectIQ/Devices"
HEADER = "GENERATED by tools/gen_icons.py from assets/icons/src and tools/icons.yaml. Do not edit by hand."
XSD = "https://developer.garmin.com/downloads/connect-iq/resources.xsd"
XML_ROOT = f'xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="{XSD}"'
PALETTE_LEVELS = (0, 85, 170, 255)


class Rasteriser:
    """SVG to RGBA PNG bytes through cairosvg or rsvg-convert."""

    def __init__(self) -> None:
        self.backend = ""
        try:
            import cairosvg  # type: ignore

            self._cairosvg = cairosvg
            self.backend = "cairosvg"
        except Exception:  # noqa: BLE001 - any import problem means fall back to the binary
            self._cairosvg = None
            if shutil.which("rsvg-convert"):
                self.backend = "rsvg-convert"
        if not self.backend:
            sys.exit(
                "ERROR: no SVG rasteriser. Install cairosvg (pip install cairosvg, needs libcairo) or rsvg-convert (brew install librsvg), or run: uv run tools/gen_icons.py"
            )

    def render(self, svg: Path, size: int) -> Image.Image:
        """Render an SVG to a square RGBA image of the given pixel size."""
        if self._cairosvg is not None:
            png = self._cairosvg.svg2png(
                url=str(svg), output_width=size, output_height=size
            )
        else:
            png = subprocess.run(
                ["rsvg-convert", "-w", str(size), "-h", str(size), str(svg)],
                check=True,
                capture_output=True,
            ).stdout
        return Image.open(io.BytesIO(png)).convert("RGBA")


def load_yaml(path: Path) -> dict[str, Any]:
    """Load a YAML file as a dictionary."""
    with path.open(encoding="utf-8") as handle:
        return cast(dict[str, Any], yaml.safe_load(handle))


def manifest_products() -> list[str]:
    """Product ids declared in manifest.xml."""
    return re.findall(r'<iq:product id="([^"]+)"', MANIFEST.read_text(encoding="utf-8"))


def device_info(device: str) -> tuple[int, bool]:
    """Screen width in pixels and whether the display is MIP for a device pack."""
    pack = DEVICES_DIR / device
    if not pack.exists():
        sys.exit(
            f"ERROR: device pack {device} is not installed, download it in the SDK Manager"
        )
    simulator = json.loads((pack / "simulator.json").read_text(encoding="utf-8"))
    compiler = json.loads((pack / "compiler.json").read_text(encoding="utf-8"))
    width = int(simulator["display"]["location"]["width"])
    return width, str(compiler.get("displayType", "")).lower() == "mip"


def quantise_mip(image: Image.Image) -> Image.Image:
    """Snap colours to the 64 colour palette and alpha to 1 bit."""
    raw = image.tobytes()
    out = bytearray(len(raw))
    for i in range(0, len(raw), 4):
        r, g, b, a = raw[i], raw[i + 1], raw[i + 2], raw[i + 3]
        if a < 128:
            out[i : i + 4] = b"\x00\x00\x00\x00"
        else:
            out[i : i + 4] = bytes(
                (nearest_level(r), nearest_level(g), nearest_level(b), 255)
            )
    return Image.frombytes("RGBA", image.size, bytes(out))


def nearest_level(channel: int) -> int:
    """Nearest of the four MIP channel levels."""
    return min(PALETTE_LEVELS, key=lambda level: abs(level - channel))


def resource_id(name: str) -> str:
    """Drawable id for an icon name."""
    return "ic_" + name.replace("-", "_")


def render_device(rasteriser: Rasteriser, cfg: dict[str, Any], device: str) -> int:
    """Render every icon for one device, return the number of files written."""
    width, mip = device_info(device)
    out_dir = PROJECT_DIR / f"resources-{device}" / "drawables"
    out_dir.mkdir(parents=True, exist_ok=True)
    groups = cfg["groups"]
    lines = [
        f"<drawables {XML_ROOT}>",
        f"    <!-- {HEADER} -->",
        f"    <!-- {device}: {width} px screen, {'MIP, 64 colour quantised' if mip else 'AMOLED, full colour'} -->",
    ]
    for name, group in cfg["icons"].items():
        svg = SRC_DIR / f"{name}.svg"
        if not svg.exists():
            sys.exit(f"ERROR: missing {svg.relative_to(PROJECT_DIR)}")
        size = max(8, round(width * float(groups[group]) / 100.0))
        image = rasteriser.render(svg, size)
        if mip:
            image = quantise_mip(image)
        image.save(out_dir / f"{resource_id(name)}.png", optimize=True)
        lines.append(
            f'    <bitmap id="{resource_id(name)}" filename="{resource_id(name)}.png"/>'
        )
    lines.append("</drawables>")
    (out_dir / "icons.xml").write_text("\n".join(lines) + "\n", encoding="utf-8")
    return len(cfg["icons"])


def main() -> int:
    """Entry point."""
    cfg = load_yaml(ICONS_FILE)
    rasteriser = Rasteriser()
    print(f"rasteriser: {rasteriser.backend}")
    for device in manifest_products():
        count = render_device(rasteriser, cfg, device)
        width, mip = device_info(device)
        print(
            f"{device}: {count} icons at {width} px {'MIP' if mip else 'AMOLED'} -> resources-{device}/drawables/"
        )
    return 0


if __name__ == "__main__":
    sys.exit(main())
