# /// script
# requires-python = ">=3.11"
# dependencies = ["pillow"]
# ///
"""Generate procedural background bitmaps per device.

Two kinds, both written to resources-<device>/drawables with a generated backgrounds.xml:

1. bg_topo: a topographic contour pattern for the whole dial (dial texture "topo"). Thin
   grey iso lines of a smooth pseudo random field, every fifth line a little lighter,
   masked to the round display. Seeded, so every build produces the same pattern.
2. bg_<category>: a disc of conditionDiameter percent of the screen for each weather
   category (clear, partly_cloudy, cloudy, rain, heavy_rain, snow, sleet, thunder, fog,
   wind, clear_night): a sky gradient with soft cloud blobs, streaks or a lightning bolt,
   dithered to the 64 colour palette on MIP displays.

Usage:
    uv run tools/gen_backgrounds.py
"""

from __future__ import annotations

import json
import math
import random
import re
import sys
from pathlib import Path

from PIL import Image, ImageDraw, ImageFilter

TOOLS_DIR = Path(__file__).resolve().parent
PROJECT_DIR = TOOLS_DIR.parent
MANIFEST = PROJECT_DIR / "manifest.xml"
DEVICES_DIR = Path.home() / "Library/Application Support/Garmin/ConnectIQ/Devices"
HEADER = "GENERATED by tools/gen_backgrounds.py. Do not edit by hand."
XSD = "https://developer.garmin.com/downloads/connect-iq/resources.xsd"
XML_ROOT = f'xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="{XSD}"'
LEVELS = (0, 85, 170, 255)
CONDITION_PERCENT = 30
CATEGORIES = (
    "clear",
    "partly_cloudy",
    "cloudy",
    "rain",
    "heavy_rain",
    "snow",
    "sleet",
    "thunder",
    "fog",
    "wind",
    "clear_night",
)
SKY = {
    "clear": ((70, 140, 230), (170, 210, 250)),
    "partly_cloudy": ((80, 140, 220), (180, 205, 240)),
    "cloudy": ((90, 105, 125), (160, 170, 185)),
    "rain": ((55, 70, 95), (110, 125, 150)),
    "heavy_rain": ((35, 45, 65), (85, 95, 120)),
    "snow": ((120, 130, 150), (200, 205, 215)),
    "sleet": ((90, 100, 125), (160, 165, 185)),
    "thunder": ((45, 25, 75), (110, 70, 150)),
    "fog": ((150, 155, 165), (200, 200, 205)),
    "wind": ((95, 130, 175), (175, 195, 220)),
    "clear_night": ((10, 15, 45), (35, 40, 90)),
}


def manifest_products() -> list[str]:
    """Product ids declared in manifest.xml."""
    return re.findall(r'<iq:product id="([^"]+)"', MANIFEST.read_text(encoding="utf-8"))


def device_info(device: str) -> tuple[int, bool]:
    """Screen width in pixels and whether the display is MIP."""
    pack = DEVICES_DIR / device
    simulator = json.loads((pack / "simulator.json").read_text(encoding="utf-8"))
    compiler = json.loads((pack / "compiler.json").read_text(encoding="utf-8"))
    return int(simulator["display"]["location"]["width"]), str(
        compiler.get("displayType", "")
    ).lower() == "mip"


def palette_image() -> Image.Image:
    """A palette image holding the 64 MIP colours."""
    colours: list[int] = []
    for r in LEVELS:
        for g in LEVELS:
            for b in LEVELS:
                colours += [r, g, b]
    colours += [0, 0, 0] * (256 - 64)
    image = Image.new("P", (1, 1))
    image.putpalette(colours)
    return image


def dither_to_palette(image: Image.Image) -> Image.Image:
    """Floyd Steinberg dither an RGBA image to the 64 colour palette, keeping 1 bit alpha."""
    alpha = image.getchannel("A").point(lambda v: 255 if v >= 128 else 0)
    rgb = (
        image.convert("RGB")
        .quantize(palette=palette_image(), dither=Image.Dither.FLOYDSTEINBERG)
        .convert("RGB")
    )
    result = rgb.convert("RGBA")
    result.putalpha(alpha)
    return result


def circle_mask(size: int) -> Image.Image:
    """Anti aliased circular alpha mask."""
    scale = 4
    big = Image.new("L", (size * scale, size * scale), 0)
    ImageDraw.Draw(big).ellipse((0, 0, size * scale - 1, size * scale - 1), fill=255)
    return big.resize((size, size), Image.Resampling.LANCZOS)


def field(x: float, y: float, seed: int) -> float:
    """Smooth pseudo random scalar field in [0, 1] from summed sines."""
    rng = random.Random(seed)
    value = 0.0
    for i in range(9):
        fx = rng.uniform(3.0, 11.0)
        fy = rng.uniform(3.0, 11.0)
        px = rng.uniform(0, 6.28)
        py = rng.uniform(0, 6.28)
        weight = 1.0 / (1 + i * 0.6)
        value += (
            weight
            * math.sin(fx * x + px + 0.8 * math.sin(fy * y))
            * math.cos(fy * y + py)
        )
    return (math.tanh(value * 0.9) + 1.0) / 2.0


TOPO_BLUR = 1.3
TOPO_OPACITY = 0.45


def topo(size: int, mip: bool) -> Image.Image:
    """Contour line dial background: blurred, low opacity iso lines masked to the round display.

    AMOLED keeps the softness as real alpha. MIP has no alpha blending, so the blurred grey is
    composited on black and dithered to the palette, which reads as faint dotted lines.
    """
    levels = 26
    grid = [
        [int(field(x / size, y / size, 7) * levels) for x in range(size)]
        for y in range(size)
    ]
    coverage = Image.new("L", (size, size), 0)
    pixels = coverage.load()
    for y in range(1, size - 1):
        for x in range(1, size - 1):
            level = grid[y][x]
            if (
                level != grid[y][x - 1] or level != grid[y - 1][x]
            ) and pixels is not None:
                pixels[x, y] = 255 if level % 5 == 0 else 170
    coverage = coverage.filter(ImageFilter.GaussianBlur(TOPO_BLUR))
    mask = circle_mask(size)
    if not mip:
        alpha = coverage.point(lambda v: int(v * TOPO_OPACITY))
        image = Image.new("RGBA", (size, size), (150, 150, 160, 255))
        image.putalpha(Image.composite(alpha, Image.new("L", (size, size), 0), mask))
        return image
    grey = coverage.point(lambda v: int(v * TOPO_OPACITY * 0.8))
    image = Image.merge("RGBA", (grey, grey, grey, Image.new("L", (size, size), 255)))
    image = dither_to_palette(image)
    image.putalpha(mask.point(lambda v: 255 if v >= 128 else 0))
    return image


def sky_disc(category: str, size: int, mip: bool) -> Image.Image:
    """Stylised sky inside a disc for one weather category."""
    top, bottom = SKY[category]
    image = Image.new("RGBA", (size, size), (0, 0, 0, 0))
    draw = ImageDraw.Draw(image)
    for y in range(size):
        t = y / max(1, size - 1)
        colour = tuple(int(top[i] + (bottom[i] - top[i]) * t) for i in range(3)) + (
            255,
        )
        draw.line((0, y, size, y), fill=colour)
    rng = random.Random(hash(category) & 0xFFFF)
    overlay = Image.new("RGBA", (size, size), (0, 0, 0, 0))
    over = ImageDraw.Draw(overlay)
    if category in ("clear", "clear_night"):
        glow = (255, 240, 180, 200) if category == "clear" else (240, 230, 200, 160)
        r = size // 4
        over.ellipse(
            (size // 2 - r, size // 5 - r, size // 2 + r, size // 5 + r), fill=glow
        )
        if category == "clear_night":
            for _ in range(18):
                sx, sy = rng.randint(0, size - 1), rng.randint(0, size - 1)
                over.point((sx, sy), fill=(255, 255, 255, 255))
    cloud_colour = {
        "partly_cloudy": (255, 255, 255, 230),
        "cloudy": (225, 230, 238, 230),
        "rain": (150, 160, 180, 230),
        "heavy_rain": (110, 120, 140, 235),
        "snow": (235, 238, 245, 235),
        "sleet": (200, 205, 215, 230),
        "thunder": (90, 70, 120, 235),
        "fog": (225, 225, 230, 200),
        "wind": (230, 235, 245, 210),
    }
    if category in cloud_colour:
        for _ in range(6):
            cx, cy = (
                rng.randint(size // 6, size * 5 // 6),
                rng.randint(size // 4, size * 3 // 4),
            )
            rx, ry = (
                rng.randint(size // 6, size // 3),
                rng.randint(size // 10, size // 5),
            )
            over.ellipse(
                (cx - rx, cy - ry, cx + rx, cy + ry), fill=cloud_colour[category]
            )
    overlay = overlay.filter(ImageFilter.GaussianBlur(size / 14))
    image = Image.alpha_composite(image, overlay)
    draw = ImageDraw.Draw(image)
    if category in ("rain", "heavy_rain", "sleet"):
        for _ in range(14 if category == "heavy_rain" else 8):
            x = rng.randint(0, size - 1)
            y = rng.randint(size // 2, size - 1)
            draw.line((x, y, x - 2, y + size // 12), fill=(200, 220, 245, 220), width=1)
    if category == "thunder":
        x = size // 2
        y = size // 4
        points = [(x, y)]
        while y < size - 4:
            x += rng.randint(-size // 8, size // 8)
            y += size // 7
            points.append((x, y))
        draw.line(points, fill=(230, 220, 255, 255), width=max(1, size // 40))
    if category == "wind":
        for i in range(5):
            y = size // 3 + i * size // 8
            draw.arc(
                (size // 8, y - size // 10, size * 7 // 8, y + size // 10),
                200,
                340,
                fill=(255, 255, 255, 220),
                width=1,
            )
    image.putalpha(
        Image.composite(
            image.getchannel("A"), Image.new("L", (size, size), 0), circle_mask(size)
        )
    )
    return dither_to_palette(image) if mip else image


def main() -> int:
    """Entry point."""
    for device in manifest_products():
        width, mip = device_info(device)
        out_dir = PROJECT_DIR / f"resources-{device}" / "drawables"
        out_dir.mkdir(parents=True, exist_ok=True)
        lines = [f"<drawables {XML_ROOT}>", f"    <!-- {HEADER} -->"]
        topo(width, mip).save(out_dir / "bg_topo.png", optimize=True)
        lines.append('    <bitmap id="bg_topo" filename="bg_topo.png"/>')
        disc = max(16, round(width * CONDITION_PERCENT / 100))
        for category in CATEGORIES:
            sky_disc(category, disc, mip).save(
                out_dir / f"bg_{category}.png", optimize=True
            )
            lines.append(
                f'    <bitmap id="bg_{category}" filename="bg_{category}.png"/>'
            )
        lines.append("</drawables>")
        (out_dir / "backgrounds.xml").write_text(
            "\n".join(lines) + "\n", encoding="utf-8"
        )
        print(
            f"{device}: topo {width} px and {len(CATEGORIES)} condition discs of {disc} px {'(dithered)' if mip else ''}"
        )
    return 0


if __name__ == "__main__":
    sys.exit(main())
