"""Generate Connect IQ settings resources and Monkey C keys from tools/sources.yaml.

Outputs, all marked as generated:
    resources/settings/properties.xml
    resources/settings/settings.xml
    resources/settings/watchface_config.xml
    resources/strings/generated_strings.xml
    source/settings/SettingsKeys.mc

Connect IQ only allows list settings on number properties, so every choice (skin, seconds
hand mode, page type, slot source, choice settings) is stored as the 0-based index into the
ordered list in sources.yaml. The Monkey C side maps the index back to the id through
SettingsKeys, which is why every list in sources.yaml is append only.

Usage:
    python3 tools/gen_settings.py           write all outputs, then run the consistency checks
    python3 tools/gen_settings.py --check   only check (registry, skins, outputs up to date), exit 1 on problems
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from collections.abc import Iterator
from pathlib import Path
from typing import Any, cast
from xml.sax.saxutils import escape

import yaml  # type: ignore[import-untyped]

TOOLS_DIR = Path(__file__).resolve().parent
PROJECT_DIR = TOOLS_DIR.parent
SOURCES_FILE = TOOLS_DIR / "sources.yaml"
HEADER = (
    "GENERATED by tools/gen_settings.py from tools/sources.yaml. Do not edit by hand."
)
XSD = "https://developer.garmin.com/downloads/connect-iq/resources.xsd"
XML_ROOT = f'xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="{XSD}"'
PALETTE_CHANNELS = {"00", "55", "AA", "FF"}
NAMED_COLORS = {
    "COLOR_WHITE",
    "COLOR_LT_GRAY",
    "COLOR_DK_GRAY",
    "COLOR_BLACK",
    "COLOR_RED",
    "COLOR_DK_RED",
    "COLOR_ORANGE",
    "COLOR_YELLOW",
    "COLOR_GREEN",
    "COLOR_DK_GREEN",
    "COLOR_BLUE",
    "COLOR_DK_BLUE",
    "COLOR_PURPLE",
    "COLOR_PINK",
    "COLOR_TRANSPARENT",
}
COLOR_REFS = {"accent"}
COLOR_KEY = re.compile(r"[cC]olor$")
EMPTY = "Empty"


def load_config() -> dict[str, Any]:
    """Load and return the YAML configuration."""
    with SOURCES_FILE.open(encoding="utf-8") as handle:
        return cast(dict[str, Any], yaml.safe_load(handle))


def ids(items: list[dict[str, Any]]) -> list[str]:
    """Ordered id strings of a YAML list of {id, ...} entries."""
    return [str(item["id"]) for item in items]


def slot_key(page: int, slot: int) -> str:
    """Property key for a 1-based page and slot."""
    return f"page{page}slot{slot}"


def page_type_key(page: int) -> str:
    """Property key for the type of a 1-based page."""
    return f"page{page}type"


def complication_uid(page: int, slot: int) -> int:
    """On-device editor complication id for a 1-based page and slot."""
    return page * 10 + slot


def const_name(key: str) -> str:
    """Convert a camelCase property key to an UPPER_SNAKE constant name."""
    return re.sub(r"(?<!^)(?=[A-Z])", "_", key).upper()


def page_defaults(cfg: dict[str, Any]) -> list[list[str]]:
    """Default source ids per page, padded with Empty pages up to the maximum."""
    pages = cfg["pages"]
    slots = int(pages["slots_per_page"])
    known = ids(cfg["sources"])
    result: list[list[str]] = []
    for index in range(int(pages["max"])):
        row = (
            [str(x) for x in pages["defaults"][index]]
            if index < len(pages["defaults"])
            else [EMPTY] * slots
        )
        if len(row) != slots:
            raise ValueError(f"page {index + 1} defaults must have {slots} entries")
        unknown = [x for x in row if x not in known]
        if unknown:
            raise ValueError(
                f"page {index + 1} defaults reference unknown sources {unknown}"
            )
        result.append(row)
    return result


def page_types(cfg: dict[str, Any]) -> list[str]:
    """Default page type id per page, padded with the first type."""
    known = ids(cfg["page_types"])
    defaults = [str(x) for x in cfg["pages"].get("default_types", [])]
    unknown = [x for x in defaults if x not in known]
    if unknown:
        raise ValueError(f"default_types reference unknown page types {unknown}")
    return [
        defaults[i] if i < len(defaults) else known[0]
        for i in range(int(cfg["pages"]["max"]))
    ]


def list_setting(
    key: str, title_id: str, labels: list[str], indent: int = 4
) -> list[str]:
    """Render a list setting whose values are the 0-based positions of the labels."""
    pad = " " * indent
    lines = [
        f'{pad}<setting propertyKey="@Properties.{key}" title="@Strings.{title_id}">',
        f'{pad}    <settingConfig type="list">',
    ]
    lines += [
        f'{pad}        <listEntry value="{index}">{label}</listEntry>'
        for index, label in enumerate(labels)
    ]
    lines += [f"{pad}    </settingConfig>", f"{pad}</setting>"]
    return lines


def numeric_setting(
    key: str, title_id: str, low: int, high: int, indent: int = 4
) -> list[str]:
    """Render a numeric setting element with bounds."""
    pad = " " * indent
    return [
        f'{pad}<setting propertyKey="@Properties.{key}" title="@Strings.{title_id}">',
        f'{pad}    <settingConfig type="numeric" min="{low}" max="{high}"/>',
        f"{pad}</setting>",
    ]


def boolean_setting(key: str, title_id: str, indent: int = 4) -> list[str]:
    """Render a boolean setting element."""
    pad = " " * indent
    return [
        f'{pad}<setting propertyKey="@Properties.{key}" title="@Strings.{title_id}">',
        f'{pad}    <settingConfig type="boolean"/>',
        f"{pad}</setting>",
    ]


def render_properties(cfg: dict[str, Any]) -> str:
    """Render properties.xml. Choice properties hold indices into the id lists in SettingsKeys.mc."""
    skin_index = ids(cfg["skins"]).index(str(cfg["default_skin"]))
    source_ids = ids(cfg["sources"])
    type_ids = ids(cfg["page_types"])
    lines = [f"<properties {XML_ROOT}>", f"    <!-- {HEADER} -->"]
    lines.append(
        "    <!-- Choice properties hold the 0-based index into the matching id list in SettingsKeys.mc. -->"
    )
    lines.append(f'    <property id="skinId" type="number">{skin_index}</property>')
    lines.append(
        f'    <property id="pageCount" type="number">{cfg["pages"]["default_count"]}</property>'
    )
    lines.append('    <property id="secondsHandMode" type="number">0</property>')
    for setting in cfg["number_settings"]:
        lines.append(
            f'    <property id="{setting["key"]}" type="number">{setting["default"]}</property>'
        )
    for setting in cfg["choice_settings"]:
        lines.append(
            f'    <property id="{setting["key"]}" type="number">{ids(setting["options"]).index(str(setting["default"]))}</property>'
        )
    for setting in cfg["boolean_settings"]:
        lines.append(
            f'    <property id="{setting["key"]}" type="boolean">{"true" if setting["default"] else "false"}</property>'
        )
    for page, page_type in enumerate(page_types(cfg), start=1):
        lines.append(
            f'    <property id="{page_type_key(page)}" type="number">{type_ids.index(page_type)}</property>'
        )
    for page, row in enumerate(page_defaults(cfg), start=1):
        for slot, source in enumerate(row, start=1):
            lines.append(
                f'    <property id="{slot_key(page, slot)}" type="number">{source_ids.index(source)}</property>'
            )
    lines.append("</properties>")
    return "\n".join(lines) + "\n"


def render_settings(cfg: dict[str, Any]) -> str:
    """Render settings.xml, the phone-side settings UI."""
    lines = [f"<settings {XML_ROOT}>", f"    <!-- {HEADER} -->"]
    lines += list_setting(
        "skinId",
        "set_skinId",
        [f"@Strings.skin_{skin_id}" for skin_id in ids(cfg["skins"])],
    )
    lines += numeric_setting("pageCount", "set_pageCount", 1, int(cfg["pages"]["max"]))
    lines += list_setting(
        "secondsHandMode",
        "set_secondsHandMode",
        [f"@Strings.shm_{mode}" for mode in ids(cfg["seconds_hand_modes"])],
    )
    for setting in cfg["number_settings"]:
        lines += numeric_setting(
            setting["key"],
            f"set_{setting['key']}",
            int(setting["min"]),
            int(setting["max"]),
        )
    for setting in cfg["choice_settings"]:
        lines += list_setting(
            setting["key"],
            f"set_{setting['key']}",
            [f"@Strings.opt_{option_id}" for option_id in ids(setting["options"])],
        )
    for setting in cfg["boolean_settings"]:
        lines += boolean_setting(setting["key"], f"set_{setting['key']}")
    source_labels = [f"@Strings.src_{source_id}" for source_id in ids(cfg["sources"])]
    type_labels = [f"@Strings.ptype_{type_id}" for type_id in ids(cfg["page_types"])]
    slots = int(cfg["pages"]["slots_per_page"])
    for page in range(1, int(cfg["pages"]["max"]) + 1):
        lines.append(f'    <group id="page{page}" title="@Strings.page_{page}">')
        lines += list_setting(
            page_type_key(page), "set_pageType", type_labels, indent=8
        )
        for slot in range(1, slots + 1):
            lines += list_setting(
                slot_key(page, slot), f"slot_{slot}", source_labels, indent=8
            )
        lines.append("    </group>")
    lines.append("</settings>")
    return "\n".join(lines) + "\n"


def render_strings(cfg: dict[str, Any]) -> str:
    """Render generated_strings.xml with every label the settings and editor reference."""
    lines = [f"<strings {XML_ROOT}>", f"    <!-- {HEADER} -->"]

    def add(string_id: str, text: str) -> None:
        lines.append(f'    <string id="{string_id}">{escape(text)}</string>')

    add("set_skinId", "Skin")
    add("set_pageCount", f"Active pages (1 to {cfg['pages']['max']})")
    add("set_secondsHandMode", "Seconds hand")
    add("set_pageType", "Page type")
    for setting in (
        cfg["number_settings"] + cfg["choice_settings"] + cfg["boolean_settings"]
    ):
        add(f"set_{setting['key']}", str(setting["label"]))
    for page in range(1, int(cfg["pages"]["max"]) + 1):
        add(f"page_{page}", f"Page {page}")
    for slot in range(1, int(cfg["pages"]["slots_per_page"]) + 1):
        add(f"slot_{slot}", f"Slot {slot}")
    for skin in cfg["skins"]:
        add(f"skin_{skin['id']}", str(skin["label"]))
    for mode in cfg["seconds_hand_modes"]:
        add(f"shm_{mode['id']}", str(mode["label"]))
    for page_type in cfg["page_types"]:
        add(f"ptype_{page_type['id']}", str(page_type["label"]))
    for source in cfg["sources"]:
        add(f"src_{source['id']}", str(source["label"]))
        add(f"srcs_{source['id']}", str(source.get("short", source["label"])).upper())
    seen: set[str] = set()
    for setting in cfg["choice_settings"]:
        for option in setting["options"]:
            if str(option["id"]) not in seen:
                seen.add(str(option["id"]))
                add(f"opt_{option['id']}", str(option["label"]))
    lines.append("</strings>")
    return "\n".join(lines) + "\n"


def render_watchface_config(cfg: dict[str, Any]) -> str:
    """Render watchface_config.xml for the on-device editor (styles = skins, complications = slots)."""
    lines = [
        f"<resources {XML_ROOT}>",
        f"    <!-- {HEADER} -->",
        "    <watchface-config>",
        "        <styles>",
    ]
    for index, skin in enumerate(cfg["skins"], start=1):
        default = ' default="true"' if skin["id"] == cfg["default_skin"] else ""
        lines.append(
            f'            <style id="{index}" label="@Strings.skin_{skin["id"]}"{default}/>'
        )
    lines += ["        </styles>", "        <data>"]
    mappable = [
        (str(s["id"]), str(s["complication"]))
        for s in cfg["sources"]
        if s["complication"]
    ]
    type_of = dict(mappable)
    for page, row in enumerate(page_defaults(cfg), start=1):
        for slot, source in enumerate(row, start=1):
            lines.append(
                f'            <complication id="{complication_uid(page, slot)}">'
            )
            default_type = type_of.get(source)
            for _, complication in mappable:
                attr = ' default="true"' if complication == default_type else ""
                lines.append(
                    f"                <type{attr}>Complications.{complication}</type>"
                )
            lines.append("            </complication>")
    lines += [
        "        </data>",
        '        <dataColors allowAny="true"/>',
        '        <accentColors allowAny="true"/>',
        "    </watchface-config>",
        "</resources>",
    ]
    return "\n".join(lines) + "\n"


def mc_string_list(items: list[str]) -> str:
    """Render a Monkey C array literal of strings."""
    return "[" + ", ".join(f'"{item}"' for item in items) + "]"


def render_settings_keys(cfg: dict[str, Any]) -> str:
    """Render source/settings/SettingsKeys.mc."""
    pages = cfg["pages"]
    max_pages = int(pages["max"])
    slots = int(pages["slots_per_page"])
    lines = [
        f"// {HEADER}",
        "import Toybox.Lang;",
        "",
        "//! Property keys, limits and defaults shared by Settings.mc and the generated resources.",
        "module SettingsKeys {",
    ]
    lines += [
        '    const SKIN_ID = "skinId";',
        '    const PAGE_COUNT = "pageCount";',
        '    const SECONDS_HAND_MODE = "secondsHandMode";',
    ]
    for setting in cfg["number_settings"]:
        name = const_name(str(setting["key"]))
        lines.append(f'    const {name} = "{setting["key"]}";')
        lines.append(f"    const {name}_DEFAULT = {int(setting['default'])};")
        lines.append(f"    const {name}_MIN = {int(setting['min'])};")
        lines.append(f"    const {name}_MAX = {int(setting['max'])};")
    for setting in cfg["choice_settings"]:
        name = const_name(str(setting["key"]))
        lines.append(f'    const {name} = "{setting["key"]}";')
        lines.append(f'    const {name}_DEFAULT = "{setting["default"]}";')
        lines.append(
            f"    var {name}_OPTIONS as Array<String> = {mc_string_list(ids(setting['options']))};"
        )
    for setting in cfg["boolean_settings"]:
        name = const_name(str(setting["key"]))
        lines.append(f'    const {name} = "{setting["key"]}";')
        lines.append(
            f"    const {name}_DEFAULT = {'true' if setting['default'] else 'false'};"
        )
    lines += [
        f"    const MAX_PAGES = {max_pages};",
        f"    const SLOTS_PER_PAGE = {slots};",
        f"    const DEFAULT_PAGE_COUNT = {int(pages['default_count'])};",
    ]
    lines += [
        f'    const DEFAULT_SKIN_ID = "{cfg["default_skin"]}";',
        f'    const DEFAULT_SECONDS_HAND_MODE = "{cfg["seconds_hand_modes"][0]["id"]}";',
        f'    const EMPTY_SOURCE_ID = "{EMPTY}";',
    ]
    lines.append(
        "    //! Ordered as in sources.yaml. Phone settings store indices into these lists, so only append."
    )
    lines.append(
        f"    var SKIN_IDS as Array<String> = {mc_string_list(ids(cfg['skins']))};"
    )
    lines.append(
        f"    var SECONDS_HAND_MODES as Array<String> = {mc_string_list(ids(cfg['seconds_hand_modes']))};"
    )
    lines.append(
        f"    var SOURCE_IDS as Array<String> = {mc_string_list(ids(cfg['sources']))};"
    )
    lines.append(
        f"    var PAGE_TYPE_IDS as Array<String> = {mc_string_list(ids(cfg['page_types']))};"
    )
    lines.append(
        f"    var DEFAULT_PAGE_TYPES as Array<String> = {mc_string_list(page_types(cfg))};"
    )
    source_index = {
        source_id: index for index, source_id in enumerate(ids(cfg["sources"]))
    }
    lines.append("    //! Default source index (into SOURCE_IDS) per page and slot.")
    lines.append("    var DEFAULT_SLOTS as Array<Array<Number>> = [")
    lines += [
        f"        [{', '.join(str(source_index[source]) for source in row)}],"
        for row in page_defaults(cfg)
    ]
    lines.append("    ];")
    lines += [
        "",
        "    //! Property key of a 0-based page and slot (built on demand, only at reload).",
        "    function slotKey(page as Number, slot as Number) as String {",
        '        return "page" + (page + 1) + "slot" + (slot + 1);',
        "    }",
        "",
        "    //! Property key of a 0-based page's type.",
        "    function pageTypeKey(page as Number) as String {",
        '        return "page" + (page + 1) + "type";',
        "    }",
        "",
        "    //! Default source ids of a 0-based page.",
        "    function defaultSlotIds(page as Number) as Array<String> {",
        "        var row = DEFAULT_SLOTS[page];",
        "        var result = [] as Array<String>;",
        "        for (var i = 0; i < row.size(); i++) {",
        "            result.add(SOURCE_IDS[row[i]]);",
        "        }",
        "        return result;",
        "    }",
        "",
        "    //! On-device editor complication id for a 0-based page and slot.",
        "    function complicationUid(page as Number, slot as Number) as Number {",
        "        return (page + 1) * 10 + (slot + 1);",
        "    }",
        "",
        "    //! 0-based page for an editor complication id.",
        "    function pageForUid(uid as Number) as Number {",
        "        return uid / 10 - 1;",
        "    }",
        "",
        "    //! 0-based slot for an editor complication id.",
        "    function slotForUid(uid as Number) as Number {",
        "        return uid % 10 - 1;",
        "    }",
        "}",
    ]
    return "\n".join(lines) + "\n"


CORE_KEYS = (
    "id",
    "name",
    "colors",
    "ticks",
    "numerals",
    "hands",
    "secondsHandMode",
    "slots",
    "pageIndicator",
    "hitboxPaddingPercent",
    "dial",
    "panels",
    "battery",
)


LAYOUT_KEYS = ("dial", "panels", "battery")


def split_skin(skin_id: str) -> tuple[str, str, str]:
    """Split an authored skin JSON into core, layout and pages parts (compact JSON)."""
    data = json.loads(
        (PROJECT_DIR / "resources/skins" / f"{skin_id}.json").read_text(
            encoding="utf-8"
        )
    )
    core = {
        key: value
        for key, value in data.items()
        if key in CORE_KEYS and key not in LAYOUT_KEYS
    }
    layout = {key: value for key, value in data.items() if key in LAYOUT_KEYS}
    pages = {key: value for key, value in data.items() if key not in CORE_KEYS}
    pages["id"] = skin_id
    compact = (",", ":")
    return (
        json.dumps(core, separators=compact) + "\n",
        json.dumps(layout, separators=compact) + "\n",
        json.dumps(pages, separators=compact) + "\n",
    )


def render_skins_xml(cfg: dict[str, Any]) -> str:
    """Render resources/skins/skins.xml pointing at the generated split files."""
    lines = [
        f"<jsonDataResources {XML_ROOT}>",
        f"    <!-- {HEADER} Authored skins live in resources/skins/<id>.json. -->",
    ]
    for skin_id in ids(cfg["skins"]):
        for part in ("", "_layout", "_pages"):
            file_part = part if part else "_core"
            lines.append(
                f'    <jsonData id="skin_{skin_id}{part}" filename="gen/{skin_id}{file_part}.json"/>'
            )
    lines.append("</jsonDataResources>")
    return "\n".join(lines) + "\n"


def skin_outputs(cfg: dict[str, Any]) -> dict[Path, str]:
    """Generated split skin files."""
    result: dict[Path, str] = {
        PROJECT_DIR / "resources/skins/skins.xml": render_skins_xml(cfg)
    }
    for skin_id in ids(cfg["skins"]):
        if (PROJECT_DIR / "resources/skins" / f"{skin_id}.json").exists():
            core, layout, pages = split_skin(skin_id)
            result[PROJECT_DIR / "resources/skins/gen" / f"{skin_id}_layout.json"] = (
                layout
            )
            result[PROJECT_DIR / "resources/skins/gen" / f"{skin_id}_core.json"] = core
            result[PROJECT_DIR / "resources/skins/gen" / f"{skin_id}_pages.json"] = (
                pages
            )
    return result


def outputs(cfg: dict[str, Any]) -> dict[Path, str]:
    """Map every output path to its rendered content."""
    result = skin_outputs(cfg)
    result.update(main_outputs(cfg))
    return result


def main_outputs(cfg: dict[str, Any]) -> dict[Path, str]:
    """Settings, strings, editor config and Monkey C keys."""
    return {
        PROJECT_DIR / "resources/settings/properties.xml": render_properties(cfg),
        PROJECT_DIR / "resources/settings/settings.xml": render_settings(cfg),
        PROJECT_DIR
        / "resources/settings/watchface_config.xml": render_watchface_config(cfg),
        PROJECT_DIR / "resources/strings/generated_strings.xml": render_strings(cfg),
        PROJECT_DIR / "source/settings/SettingsKeys.mc": render_settings_keys(cfg),
    }


def iter_skin_colors(data: Any, path: str = "") -> Iterator[tuple[str, Any]]:
    """Yield (path, value) for every field whose key ends in color/Color, at any depth."""
    if isinstance(data, dict):
        for key, value in data.items():
            child = f"{path}.{key}" if path else str(key)
            if COLOR_KEY.search(str(key)) or (path == "colors"):
                yield child, value
            else:
                yield from iter_skin_colors(value, child)
    elif isinstance(data, list):
        for index, value in enumerate(data):
            yield from iter_skin_colors(value, f"{path}[{index}]")


def valid_color(value: Any) -> bool:
    """True when a colour is a reference, a safe named colour, or a hex value on the 64 colour MIP palette."""
    if value in COLOR_REFS or value in NAMED_COLORS:
        return True
    if isinstance(value, str) and value.startswith("0x") and len(value) == 8:
        channels = [value[2:4].upper(), value[4:6].upper(), value[6:8].upper()]
        return all(channel in PALETTE_CHANNELS for channel in channels)
    return False


def check_skins(cfg: dict[str, Any]) -> list[str]:
    """Validate every declared skin: file exists, id matches, colours are palette safe."""
    errors: list[str] = []
    for skin in cfg["skins"]:
        path = PROJECT_DIR / "resources/skins" / f"{skin['id']}.json"
        if not path.exists():
            errors.append(f"missing skin file {path.relative_to(PROJECT_DIR)}")
            continue
        data = json.loads(path.read_text(encoding="utf-8"))
        if data.get("id") != skin["id"]:
            errors.append(f"{path.name}: id field must be '{skin['id']}'")
        errors += [
            f"{path.name}: {field} = {value!r} is not on the 64 colour palette"
            for field, value in iter_skin_colors(data)
            if not valid_color(value)
        ]
    return errors


def check_registry(cfg: dict[str, Any]) -> list[str]:
    """Verify the Monkey C registries reference every source id and skin id."""
    errors: list[str] = []
    registry = PROJECT_DIR / "source/data/DataSourceRegistry.mc"
    registry_text = registry.read_text(encoding="utf-8") if registry.exists() else ""
    for source_id in ids(cfg["sources"]):
        if f"new {source_id}Source(" not in registry_text:
            errors.append(f"DataSourceRegistry.mc does not register {source_id}Source")
        if not (PROJECT_DIR / "source/data/sources" / f"{source_id}.mc").exists():
            errors.append(f"missing source/data/sources/{source_id}.mc")
    skin_registry = PROJECT_DIR / "source/skin/SkinRegistry.mc"
    skin_text = (
        skin_registry.read_text(encoding="utf-8") if skin_registry.exists() else ""
    )
    errors += [
        f"SkinRegistry.mc has no entry for skin {skin_id}"
        for skin_id in ids(cfg["skins"])
        if f'"{skin_id}"' not in skin_text
    ]
    return errors


def check_outputs(cfg: dict[str, Any]) -> list[str]:
    """Report generated files that are missing or differ from the YAML."""
    errors: list[str] = []
    for path, content in outputs(cfg).items():
        if not path.exists() or path.read_text(encoding="utf-8") != content:
            errors.append(
                f"{path.relative_to(PROJECT_DIR)} is out of date, run tools/gen_settings.py"
            )
    return errors


def main(argv: list[str] | None = None) -> int:
    """Entry point."""
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument(
        "--check", action="store_true", help="validate only, do not write"
    )
    args = parser.parse_args(argv)
    cfg = load_config()
    if not args.check:
        for path, content in outputs(cfg).items():
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
            print(f"wrote {path.relative_to(PROJECT_DIR)}")
    errors = check_skins(cfg) + check_registry(cfg) + check_outputs(cfg)
    for error in errors:
        print(f"ERROR: {error}", file=sys.stderr)
    print("ok" if not errors else f"{len(errors)} problem(s)")
    return 1 if errors else 0


if __name__ == "__main__":
    sys.exit(main())
