# /// script
# requires-python = ">=3.11"
# dependencies = ["pillow", "pyyaml"]
# ///
"""Rasterise TTF fonts from assets/fonts into per device Connect IQ bitmap fonts.

For every product in manifest.xml and every font in tools/fonts.yaml a BMFont text file
plus a PNG atlas is written to resources-<device>/fonts/, with a generated fonts.xml. The
pixel size is percent of the screen width. MIP devices get one bit glyph coverage, AMOLED
keeps anti aliasing. Also checks that the widest expected value strings fit a panel.

Usage:
    uv run tools/gen_fonts.py
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path
from typing import Any, cast

import yaml  # type: ignore[import-untyped]
from PIL import Image, ImageDraw, ImageFont

TOOLS_DIR = Path(__file__).resolve().parent
PROJECT_DIR = TOOLS_DIR.parent
FONT_DIR = PROJECT_DIR / "assets/fonts"
FONTS_FILE = TOOLS_DIR / "fonts.yaml"
MANIFEST = PROJECT_DIR / "manifest.xml"
DEVICES_DIR = Path.home() / "Library/Application Support/Garmin/ConnectIQ/Devices"
HEADER = "GENERATED by tools/gen_fonts.py from assets/fonts and tools/fonts.yaml. Do not edit by hand."
XSD = "https://developer.garmin.com/downloads/connect-iq/resources.xsd"
XML_ROOT = f'xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="{XSD}"'
ATLAS_WIDTH = 512
PADDING = 1
WIDEST_SAMPLES = ("100%", "-12°", "1013", "29.92", "88:88")


def load_yaml(path: Path) -> dict[str, Any]:
    """Load a YAML file as a dictionary."""
    with path.open(encoding="utf-8") as handle:
        return cast(dict[str, Any], yaml.safe_load(handle))


def manifest_products() -> list[str]:
    """Product ids declared in manifest.xml."""
    return re.findall(r'<iq:product id="([^"]+)"', MANIFEST.read_text(encoding="utf-8"))


def device_info(device: str) -> tuple[int, bool]:
    """Screen width in pixels and whether the display is MIP for a device pack."""
    pack = DEVICES_DIR / device
    simulator = json.loads((pack / "simulator.json").read_text(encoding="utf-8"))
    compiler = json.loads((pack / "compiler.json").read_text(encoding="utf-8"))
    return int(simulator["display"]["location"]["width"]), str(
        compiler.get("displayType", "")
    ).lower() == "mip"


class Glyph:
    """One rendered glyph and its placement in the atlas."""

    def __init__(
        self, char: str, image: Image.Image, offset_x: int, offset_y: int, advance: int
    ) -> None:
        self.char = char
        self.image = image
        self.offset_x = offset_x
        self.offset_y = offset_y
        self.advance = advance
        self.x = 0
        self.y = 0


def render_glyphs(
    font: ImageFont.FreeTypeFont, chars: str, one_bit: bool
) -> list[Glyph]:
    """Render every character to a tight coverage bitmap."""
    glyphs: list[Glyph] = []
    ascent, _ = font.getmetrics()
    for char in chars:
        box = font.getbbox(char)
        left, top, right, bottom = int(box[0]), int(box[1]), int(box[2]), int(box[3])
        width = max(1, right - left)
        height = max(1, bottom - top)
        canvas = Image.new("L", (width, height), 0)
        ImageDraw.Draw(canvas).text((-left, -top), char, font=font, fill=255)
        if one_bit:
            canvas = canvas.point(lambda v: 255 if v >= 128 else 0)
        advance = int(round(font.getlength(char)))
        glyphs.append(Glyph(char, canvas, left, top, advance))
    del ascent
    return glyphs


def pack(glyphs: list[Glyph]) -> tuple[int, int]:
    """Row pack glyphs into an atlas, return its size."""
    x = PADDING
    y = PADDING
    row_height = 0
    for glyph in glyphs:
        if x + glyph.image.width + PADDING > ATLAS_WIDTH:
            x = PADDING
            y += row_height + PADDING
            row_height = 0
        glyph.x = x
        glyph.y = y
        x += glyph.image.width + PADDING
        row_height = max(row_height, glyph.image.height)
    return ATLAS_WIDTH, y + row_height + PADDING


def write_font(
    out_dir: Path, name: str, spec: dict[str, Any], width_px: int, one_bit: bool
) -> tuple[int, int]:
    """Write <name>.fnt and <name>.png. Returns (pixel size, line height)."""
    size = max(8, round(width_px * float(spec["percent"]) / 100.0))
    font = ImageFont.truetype(str(FONT_DIR / str(spec["ttf"])), size)
    ascent, descent = font.getmetrics()
    glyphs = render_glyphs(font, str(spec["chars"]), one_bit)
    atlas_w, atlas_h = pack(glyphs)
    atlas = Image.new("RGBA", (atlas_w, atlas_h), (0, 0, 0, 0))
    lines = [
        f'info face="{Path(str(spec["ttf"])).stem}" size=-{size} bold=0 italic=0 charset="" unicode=1 stretchH=100 smooth={0 if one_bit else 1} aa=1 padding=0,0,0,0 spacing=1,1 outline=0',
        f"common lineHeight={ascent + descent} base={ascent} scaleW={atlas_w} scaleH={atlas_h} pages=1 packed=0 alphaChnl=0 redChnl=4 greenChnl=4 blueChnl=4",
        f'page id=0 file="{name}.png"',
        f"chars count={len(glyphs)}",
    ]
    for glyph in glyphs:
        white = Image.new("RGBA", glyph.image.size, (255, 255, 255, 255))
        white.putalpha(glyph.image)
        atlas.paste(white, (glyph.x, glyph.y))
        lines.append(
            f"char id={ord(glyph.char)} x={glyph.x} y={glyph.y} width={glyph.image.width} height={glyph.image.height} "
            f"xoffset={glyph.offset_x} yoffset={glyph.offset_y} xadvance={glyph.advance} page=0 chnl=15"
        )
    atlas.save(out_dir / f"{name}.png", optimize=True)
    (out_dir / f"{name}.fnt").write_text("\n".join(lines) + "\n", encoding="utf-8")
    return size, ascent + descent


def check_widths(
    font_spec: dict[str, Any], width_px: int, panel_percent: float
) -> list[str]:
    """Warn when the widest expected value strings do not fit inside a panel."""
    size = max(8, round(width_px * float(font_spec["percent"]) / 100.0))
    font = ImageFont.truetype(str(FONT_DIR / str(font_spec["ttf"])), size)
    limit = width_px * panel_percent / 100.0 * 0.86
    warnings: list[str] = []
    for sample in WIDEST_SAMPLES:
        if all(ch in str(font_spec["chars"]) for ch in sample):
            length = font.getlength(sample)
            if length > limit + 1.0:
                warnings.append(
                    f"'{sample}' is {length:.0f} px, wider than the {limit:.0f} px panel interior at {width_px} px"
                )
    return warnings


def panel_percent() -> float:
    """Panel diameter percent from the classic skin, default 24."""
    skin = json.loads(
        (PROJECT_DIR / "resources/skins/classic.json").read_text(encoding="utf-8")
    )
    return float(skin.get("panels", {}).get("diameter", 24))


def main() -> int:
    """Entry point."""
    cfg = load_yaml(FONTS_FILE)
    problems = 0
    for device in manifest_products():
        width_px, mip = device_info(device)
        out_dir = PROJECT_DIR / f"resources-{device}" / "fonts"
        out_dir.mkdir(parents=True, exist_ok=True)
        lines = [f"<fonts {XML_ROOT}>", f"    <!-- {HEADER} -->"]
        for name, spec in cfg["fonts"].items():
            size, line_height = write_font(out_dir, name, spec, width_px, mip)
            lines.append(
                f'    <font id="{name}" filename="{name}.fnt" filter="{spec["chars"]}"/>'
            )
            print(
                f"{device}: {name} {size} px (line height {line_height}) {'1 bit' if mip else 'anti aliased'}"
            )
        lines.append("</fonts>")
        (out_dir / "fonts.xml").write_text("\n".join(lines) + "\n", encoding="utf-8")
        for warning in check_widths(cfg["fonts"]["Value"], width_px, panel_percent()):
            print(f"WARNING {device}: {warning}")
            problems += 1
    return 1 if problems else 0


if __name__ == "__main__":
    sys.exit(main())
